name: Frappe CD - Deploy to Production

# Trigger on push to main or manual trigger
on:
  push:
    branches:
      - main
  workflow_dispatch:  # allows manual trigger too

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production  # This will pause deployment until approved in GitHub UI

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/new-bench
            git pull
            bench --site deepika.local get-app https://github.com/DeepikaChhlotre13/frappe-testing-ci-cd.git
            bench --site deepika.local migrate
            bench build
            sudo supervisorctl restart all
